# Generated by Django 5.0.1 on 2024-08-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_studentprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(default='Anonymous', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(default='Anonymous', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('CHE', 'Chemical Engineering'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('IE', 'Industrial Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('EE', 'Electrical Engineering')], max_length=100),
        ),
    ]
